apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-backup-cronjob
spec:
  schedule: "*/5 * * * *"  # Run every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-backup-container
            image: my-google-drive-backup:latest
          restartPolicy: OnFailure

